theme: jekyll-theme-cayman
title: NetworkGT

navbar-links:
  Home: "https://bjornnyberg.github.io/NetworkGT/"
  Download: "https://github.com/BjornNyberg/NetworkGT/archive/V0.1.1.zip"
  Wiki: "https://github.com/BjornNyberg/NetworkGT/wiki"
